/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * KZG wrapper class, holding the Trusted Setup parameters for computation.
 * The internal settings are thread-safe and used across parallel operations.
 */
export declare class KzgWrapper {
  /**
   * Loads the KZG Trusted Setup from G1/G2 monomial and Lagrange byte arrays.
   * Returns: KzgWrapper instance or a specific error message on failure.
   */
  static loadKzg(g1MonomialBytes: Uint8Array, g1LagrangeBytes: Uint8Array, g2MonomialBytes: Uint8Array): KzgWrapper
  /**
   * Converts a single blob into a KZG commitment.
   * - `blob_bytes`: The blob byte array.
   * Returns: Commitment as a "0x..." prefixed hex string.
   */
  blobToCommitment(blobBytes: Uint8Array): string
  /**
   * **Batch** and **concurrently** converts multiple blobs to KZG commitments using Rayon.
   * - `blobs_bytes`: A vector of blob byte arrays.
   * Returns: A vector of commitment strings.
   */
  blobToCommitmentBatch(blobsBytes: Array<Uint8Array>): Array<string>
  /**
   * Computes the KZG proofs for all cells of a single blob.
   * - `blob_bytes`: The blob byte array.
   * Returns: An array of proof strings (each prefixed with "0x").
   */
  computeCellProofs(blobBytes: Uint8Array): Array<string>
  /**
   * **Batch** and **concurrently** computes cell KZG proofs for multiple blobs using Rayon.
   * - `blobs_bytes`: A vector of blob byte arrays.
   * Returns: A 2D array of proof strings.
   */
  computeCellProofsBatch(blobsBytes: Array<Uint8Array>): Array<Array<string>>
}
