name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: napi-rs/napi-rs/.github/workflows/ci.yml@v2
    with:
      package-name: rust-kzg-node
      working-directory: .
      version: ${{ github.ref_name }}
      publish: true
      registry: https://registry.npmjs.org
      targets: |
        x86_64-pc-windows-msvc
        aarch64-pc-windows-msvc
        x86_64-apple-darwin
        aarch64-apple-darwin
        x86_64-unknown-linux-gnu
        aarch64-unknown-linux-gnu
        x86_64-unknown-linux-musl
        aarch64-unknown-linux-musl
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
